### ISSUE TITLE
kissmanga.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#124]
### Basic Information

**Test link:** `http://kissmanga.com/Manga/Yamemasu-Tsugi-No-Shokuba-Ha-Mao-Jo/Ch-004-002-004-004?id=447250`
**Category:** breakage
**Reported from:** Philippines
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

### Additional Message

Technically it blocks the comic pages as well.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://kissmanga.com/Manga/Death-March-kara-Hajimaru-Isekai-Kyousoukyoku/Ch-045----A-Disturbing-Beginning?id=448005`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.51

### Additional Message

Takes ~30 seconds to trigger, images disappear, may need to clear cookies if the site says it is under maintenance.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
I don't know if t makes much sense to add working filters as the site updates within 24 hours and considering the update frequency of uBo filters ....

**Comment by okiehsch** [comment]
Fixed, you need to clear cookies if you already triggred the detection.

**Comment by llacb47** [comment]
> Takes ~30 seconds to trigger, images disappear, may need to clear cookies if the site says it is under maintenance.
Can still reproduce this anti-adblock...

Cosmetic filter for empty spaces `kissmanga.com##iframe[src*="ads/ad"]` could be added.

**Comment by okiehsch** [comment]
I can't reproduce ant-adblock at `kissmanga.com` or `readcomiconline.to`.

**Comment by llacb47** [comment]
Hmm, how should I document it... logger and screenshots?

**Comment by okiehsch** [comment]
Well, I believe you that you get one but with a default setup using Chromium/Chrome on my end at 
````
https://kissmanga.com/Manga/Death-March-kara-Hajimaru-Isekai-Kyousoukyoku/Ch-045----A-Disturbing-Beginning?id=448005
````
I don't.

**Comment by llacb47** [comment]
Well, I mean it doesn't say `Turn off adblocker` or anything, the images does disappear. I'm using Firefox to test with default setup.

**Comment by okiehsch** [comment]
They don't dissapear on my end.
![image](https://user-images.githubusercontent.com/16838044/62404028-9539f680-b591-11e9-98fd-8002cffa9331.png)

I can't test with Firefox at the moment.

**Comment by llacb47** [comment]
After waiting 30 seconds?

**Comment by okiehsch** [comment]
That screenshot is of a tab that has been open since my first reply 10 minutes ago.
The pictures are still there.

**Comment by okiehsch** [comment]
Let's wait for somebody who can test with Firefox.

**Comment by llacb47** [comment]
Huh. This filter seems to work: `kissmanga.com##+js(abort-current-inline-script.js, isClickHide)` from https://github.com/Yumire/kiss-filters

**Comment by llacb47** [comment]
Regarding `readcomiconline.to`, it is fixed in `uBO - annoyances`. Since that is not enabled by default I encountered an anti-adblock dialog. Sorry 👍

**Comment by jspenguin2017** [comment]
@okiehsch I can reproduce anti-adblock, popup, and ads placeholders on this domain.

**Comment by okiehsch** [comment]
`kissmanga.com##+js(abort-current-inline-script.js, isClickHide)`
`kissmanga.com##iframe[src*="ads/ad"]`
works for you too?

I don't see any popup I see the ads placeholder.

**Comment by llacb47** [comment]
A few times a popup appeared from `wysasys.com` but I could not reproduce it consistently.

**Comment by jspenguin2017** [comment]
Yes, that works. 

I also get popups from `wysasys.com`, but I haven't investigate deeper what is causing it. It seems that the popups only trigger when clicking on the ads placeholders.

**Comment by jspenguin2017** [comment]
Let's call this good for now.
