### ISSUE TITLE
nbc.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#254]
### Basic Information

**Test link:** `https://www.nbc.com/the-tonight-show/video/tiffany-haddish-steve-kornacki-buddy/3815117`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 10895.78.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.65

### Additional Message

ads were not blocked

**Comment by jspenguin2017** [comment]
Server side ads insertion.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.nbc.com/the-golden-globe-awards/video/the-76th-annual-golden-globe-awards/3852737`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.87

### Additional Message

Does not play. black screen

**Comment by mapx-** [comment]
no issue (FF / chrome, uBo default setup)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.nbc.com/the-blacklist/video/olivia-olson/3930424`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 11647.104.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.nbc.com/the-blacklist/video/lady-luck/3933721`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 11647.104.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.nbc.com/the-blacklist/video/dr-lewis-powell/4059562`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.nbc.com/manifest/video/coordinated-flight/4108301`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

If you go to the page with nano enabled you get a 404 error page but if you turn it off you can get on the page fine but with ads

**Comment by jspenguin2017** [comment]
@okiehsch Minor breakage, GeoLock message not shown.

**Comment by okiehsch** [comment]
I think I fixed that yesterday,  are your filters up to date?
https://github.com/uBlockOrigin/uAssets/commit/8d95568657fe593911ec99440b8c13dbf7a585db

**Comment by jspenguin2017** [comment]
@okiehsch Yea, I updated my filters, it's still not working, although it's a minor issue. 

Actual: 
![image](https://user-images.githubusercontent.com/7283682/74071549-76457280-49c1-11ea-8e27-38c4817e1887.png)

Expected: 
![image](https://user-images.githubusercontent.com/7283682/74071557-7d6c8080-49c1-11ea-8687-ca835dcd553d.png)

**Comment by okiehsch** [comment]
Hm, weird, I tried with a non US IP and I get 
![image](https://user-images.githubusercontent.com/16838044/74071686-e1fcff00-4a04-11ea-9175-1de465d17c1a.png)

I can't reproduce your first screenshot

**Comment by okiehsch** [comment]
OK, I tried with Firefox and I can reproduce. It works fine with Chromium on my end.
I will add a fix.

**Comment by okiehsch** [comment]
Fixed.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Yep, confirmed fixed.
