### ISSUE TITLE
scat.gold

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4114]
### Basic Information

**Test link:** `https://scat.gold/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

### Additional Message

It Looks Like You Have An AdBlocker Enabled

**Comment by okiehsch** [comment]
Very NSFW.

**Comment by dumbusernameidk** [comment]
Also has unwanted popups when clicking on the site and a debugger trap.

**Comment by okiehsch** [comment]
The anti adblock is already fixed in uAssets. I can't reproduce Popups or a debugger trap using Chromium.

**Comment by dumbusernameidk** [comment]
Updated filters and still have anti-adblock + all the above. Here's the code for the debugger trap that appears `https://pastebin.com/MNS63Fxx`. As for popups it's an invisible overlay on the adblock screen it comes from one of these junk sites `jzhzm30o49gv.com`.

**Comment by okiehsch** [comment]
>Updated filters

`jzhzm30o49gv.com` has been added two days ago. https://github.com/uBlockOrigin/uAssets/commit/59224f9158d6533aa69b5c3ec97079f826dd8e64#diff-728d382ab45d1e85df51bb432db0ce90

I can reproduce the anti adblock issue today.
