### ISSUE TITLE
2conv.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#633]
### Basic Information

**Test link:** `https://2conv.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.89

### Additional Message

Ads placeholders

**Comment by jspenguin2017** [comment]
Ads placeholders. 

This one can be a bit tricky because the way column width is set.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://2conv.com/ro/downloads/mp3/yt_GuC1t0SkEkw/`
**Category:** ads
**Reported from:** Romania
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://2conv.com/en49/<br>`https://www.flvto.biz/en69/`<br>`https://www.flv2mp3.by/en12/``
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
**Extension:** Nano Adblocker 1.0.0.147

### Additional Message

Original URL: `https://2conv.com/en49/`

Pop-ups with crap RU video: `https://www.youtube.com/watch?v=ynlZttKUyAs`

A lot of a placeholders:

```
2conv.com##div[class*="ads"]
flvto.biz##div[class*="ads"]
flv2mp3.by##div[class*="ads"]
```

**Comment by llacb47** [comment]
```
2conv.com,flvto.biz,flv2mp3.by##[data-revive-zoneid]:upward(1)
2conv.com,flvto.biz,flv2mp3.by##.push-offer
```
![image](https://user-images.githubusercontent.com/16567977/82860525-e97ae200-9ee7-11ea-8d5b-38936c36d12c.png)
```
2conv.com,flvto.biz,flv2mp3.by##.interview-offer
```

**Comment by jspenguin2017** [comment]
@okiehsch Test links: 
```
https://2conv.com/en49/
https://www.flvto.biz/en69/
https://www.flv2mp3.by/en12/
```

<details>

![image](https://user-images.githubusercontent.com/7283682/83216195-e836f880-a125-11ea-9da5-e4ceaf997213.png)

![image](https://user-images.githubusercontent.com/7283682/83216083-ab6b0180-a125-11ea-82de-445f1d4742c9.png)

![image](https://user-images.githubusercontent.com/7283682/83216204-eff69d00-a125-11ea-9064-9e65e0889981.png)

</details>

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
@okiehsch I still see ads on `https://www.flv2mp3.by/en12/`. 

Fix: `flv2mp3.by##.push-in-page__item`

**Comment by krystian3w** [comment]
The sites are `pre-2020` pages: https://github.com/uBlockOrigin/uAssets/blob/1a4afe2f1bc76ae83028dfc598f98e2f12d517a4/filters/filters.txt#L13252

Also Opera may no longer need use css.

**Comment by jspenguin2017** [comment]
Could be an outdated rule, probably should be moved to the 2020 file or simply removed if it is no longer needed.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/105dc88021c46ebfbc519fdc9eeac72686c19009
https://github.com/uBlockOrigin/uAssets/commit/beed463dc670a52dafd70b0faebee2eea89ba72e
