### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#782]
### Basic Information

**Test link:** `https://timesofindia.indiatimes.com/india/2019-lok-sabha-elections-this-is-why-congresss-first-list-is-unique/articleshow/68336492.cms`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by ghajini** [comment]
@mapx-

A}
Firefox android,  ublock origin 1.18.4
1. From around the web

`https://m.timesofindia.com/india/ambani-scion-akash-weds-shloka-mehta-in-glittering-celeb-filled-ceremony/articleshow/68337344.cms`

2. Promoted stories

https://m.economictimes.com/industry/transportation/railways/jindal-rail-infra-poised-to-get-rs-18-35-crore-in-an-arbitration-case/articleshow/68322945.cms

B}
Desktop browsers issue still persist on other toi network sites..
see 
https://github.com/LiCybora/NanoDefenderFirefox/issues/113

**Comment by ghajini** [comment]
Commit
https://github.com/uBlockOrigin/uAssets/commit/516ea7d12348595592ed47b7e770a5d7d2a52ab1
doesn't help
https://github.com/NanoMeow/QuickReports/issues/782#issuecomment-471248583

**Comment by mapx-** [comment]
I cannot reproduce all the ads (I'm using a FF extension to simulate FF on mobile)

test these filters
```
m.economictimes.com##H2:has-text(/Promoted/) + DIV
m.economictimes.com##h2:has-text(/Promoted/)
||m.economictimes.com/mpetat/commons/images/rbc-red.png$image

economictimes.indiatimes.com##div h2:has(span:matches-css-before(content: /Sponsored/))
economictimes.indiatimes.com##div h2:has(span:matches-css-before(content: /Sponsored/)) + div

indiatimes.com##h2:has-text(/Promoted/) + div
indiatimes.com##h2:has-text(/Promoted/)
||media.indiatimes.in/idthat/commons/images/rbc-gray.png$image

indiatimes.com##[onclick] h5:has-text(/Ad/):xpath(../../..)
```

**Comment by ghajini** [comment]
Issue still persist at 
`m.timesofindia.com`
Described at https://github.com/NanoMeow/QuickReports/issues/782#issuecomment-471248583

**Comment by mapx-** [comment]
as I said not all are reproducible, for m.times I fixed (test it) point 2

**Comment by mapx-** [comment]
I added the filters above

**Comment by ghajini** [comment]
May be someone with Firefox android device help us as issue is still reproducible at m.timesofindia.com (URL is never of domain `indiatimes.com` on Firefox android)
Thanks for other fixes and your time

**Comment by ghajini** [comment]
@mapx- see if this helps you
Here is the way to reproduce regarding m.timesofindia.com
1.
Install this extension on your firefox

`https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher-revived/`

2. Set user agent as android

3. Visit `m.timesofindia.com` and click any article you will see `from around the web` ads
4. Click on `TOI` thumbnail at top you will see homepage ads in between articles I shown at
https://github.com/NanoMeow/QuickReports/issues/782#issuecomment-471248583

**Comment by mapx-** [comment]
I installed the addon but still ... like before => no `from around the web` section. Could I'm served other content (geo-based stuff ?)

**Comment by ghajini** [comment]
Video STR
`https://streamable.com/8z94n`

**Comment by mapx-** [comment]
test:
if you want to hide the whole `from around the web` section
`m.timesofindia.com##.promobox`
only the Ad parts
`m.timesofindia.com##.brand_ctn:has-text(/Ad:/):xpath(../..)`

**Comment by ghajini** [comment]
1.
`m.timesofindia.com##.brand_ctn:has-text(/Ad:/):xpath(../..)` will fix `from around the web` ads

2. What about homepage ads,
STR- go to homepage,  click any article then click `TOI` thumbnail at top left to return to homepage, you will see ads

**Comment by jspenguin2017** [comment]
I can reproduce ads on `https://m.timesofindia.com/` and ads placeholders on `https://www.indiatimes.com/news/india/former-navy-chief-writes-to-election-commission-to-stop-misuse-of-armed-forces-in-polls-363444.html`, but not the rest.

**Comment by mapx-** [comment]
@ghajini  does this work
`m.timesofindia.com##span:has-text(/Ad:/):xpath(../..)`

**Comment by ghajini** [comment]
It does hide very 1St ad but then when you scroll below you still see ads in between articles

**Comment by ghajini** [comment]
Can be considered fixed, thanks
